default_platform(:android)

platform :android do

  desc "build"
  lane :build do
    signing = {
      "android.injected.signing.store.file" => "/home/runner/keystore",
      "android.injected.signing.store.password" => "password",
      "android.injected.signing.key.alias" => "key0",
      "android.injected.signing.key.password" => "password"
    }
    gradle(task: 'assembleGoogle', build_type: 'Release', properties: signing)
    gradle(task: 'bundleGoogle', build_type: 'Release', properties: signing)
  end
end